### ISSUE TITLE
Ran the code and got a virus

### ISSUE THREAD

**Issue by dershao** [arialdomartini/morris-worm#5]

**Comment by grandsir** [comment]
HAHAHAHAHAHAHAHAHA

**Comment by Voy463** [comment]
how are you so dumb do to this

**Comment by dershao** [comment]
I downloaded the Morris Bird and was able to solve the problem

**Comment by Slof1nn** [comment]
`RIP`

**Comment by ghost** [comment]
LOL ITS MORRIS WORM WHAT KIND OF IDIOT YOU NEED TO BE TO ACTUALLY BE STUPID ENOUGHT TO THINK LIKE "OH WE GOT A GAME HERE" *RUNS MORRIS* LIKE C*MON MANXD

**Comment by MyLifeIsSakura** [comment]
obviusly u got a fcking virus dumbass its a very dangerous worm idioit

**Comment by ashbit06** [comment]
lmao l+bozo

**Comment by therealfyodordostoevsky** [comment]
I mean... Your first demonstration of stupidity was downloading these files in the first place, plus executing them? This is absolutely dumb. By the way, does this worm actually work on new operating systems? I assume this only works on Unix.
